from homeassistant.components.sensor.const import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    PERCENTAGE,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfFrequency,
    UnitOfPower,
    UnitOfReactivePower,
    UnitOfTemperature,
    UnitOfTime,
)

from custom_components.solisconnect.data.enums import DataType, PollSpeed

# base on RS485_MODBUS Communication Protocol Ver19
string_sensors = [
    # offset by -1
    {
        "register_start": 2999,
        "poll_speed": PollSpeed.FAST,
        "entities": [
            {
                "name": "Product Model",
                "unique": "solisconnect_product_model",
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["2999"],
                "multiplier": 1,
            },
            {
                "name": "DSP Software Version",
                "unique": "solisconnect_dsp_software_version",
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3000"],
                "multiplier": 1,
            },
            {
                "name": "HMI Major Version",
                "unique": "solisconnect_hmi_major_version",
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3001"],
                "multiplier": 1,
            },
            {
                "name": "AC Output Type",
                "unique": "solisconnect_ac_output_type",
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3002"],
                "multiplier": 1,
            },
            {
                "name": "DC Input Type",
                "unique": "solisconnect_dc_input_type",
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3003"],
                "multiplier": 1,
            },
            {
                "name": "Active Power",
                "unique": "solisconnect_active_power",
                "state_class": SensorStateClass.MEASUREMENT,
                "device_class": SensorDeviceClass.POWER,
                "unit_of_measurement": UnitOfPower.WATT,
                "register": ["3004", "3005"],
                "multiplier": 1,
            },
            {
                "name": "Total DC Output Power",
                "unique": "solisconnect_total_dc_output_power",
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3006", "3007"],
                "multiplier": 1,
            },
            {
                "name": "Total Energy",
                "unique": "solisconnect_total_energy",
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
                "register": ["3008", "3009"],
                "multiplier": 1,
            },
            {
                "name": "Energy This Month",
                "unique": "solisconnect_energy_this_month",
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
                "register": ["3010", "3011"],
                "multiplier": 1,
            },
            {
                "name": "Energy Last Month",
                "unique": "solisconnect_energy_last_month",
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
                "register": ["3012", "3013"],
                "multiplier": 1,
            },
            {
                "name": "Energy Today",
                "unique": "solisconnect_energy_today",
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
                "register": ["3014"],
                "multiplier": 0.1,
            },
            {
                "name": "Energy Yesterday",
                "unique": "solisconnect_energy_yesterday",
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
                "register": ["3015"],
                "multiplier": 0.1,
            },
            {
                "name": "Energy This Year",
                "unique": "solisconnect_energy_this_year",
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
                "register": ["3016", "3017"],
                "multiplier": 1,
            },
            {
                "name": "Energy Last Year",
                "unique": "solisconnect_energy_last_year",
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "device_class": SensorDeviceClass.ENERGY,
                "state_class": SensorStateClass.TOTAL_INCREASING,
                "register": ["3018", "3019"],
                "multiplier": 1,
            },
            {"type": "reserve", "register": ["3020"]},
            {
                "name": "DC Voltage 1",
                "unique": "solisconnect_dc_voltage_1",
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3021"],
                "multiplier": 0.1,
            },
            {
                "name": "DC Current 1",
                "unique": "solisconnect_dc_current_1",
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3022"],
                "multiplier": 0.1,
            },
            {
                "name": "DC Voltage 2",
                "unique": "solisconnect_dc_voltage_2",
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3023"],
                "multiplier": 0.1,
            },
            {
                "name": "DC Current 2",
                "unique": "solisconnect_dc_current_2",
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3024"],
                "multiplier": 0.1,
            },
            {
                "name": "DC Voltage 3",
                "unique": "solisconnect_dc_voltage_3",
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3025"],
                "multiplier": 0.1,
            },
            {
                "name": "DC Current 3",
                "unique": "solisconnect_dc_current_3",
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3026"],
                "multiplier": 0.1,
            },
            {
                "name": "DC Voltage 4",
                "unique": "solisconnect_dc_voltage_4",
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3027"],
                "multiplier": 0.1,
            },
            {
                "name": "DC Current 4",
                "unique": "solisconnect_dc_current_4",
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3028"],
                "multiplier": 0.1,
            },  # 30
        ],
    },
    {
        "register_start": 3033,
        "poll_speed": PollSpeed.FAST,
        "entities": [
            {
                "name": "A Phase Voltage",
                "unique": "solisconnect_inverter_a_phase_voltage",
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3033"],
                "multiplier": 0.1,
            },
            {
                "name": "B Phase Voltage",
                "unique": "solisconnect_inverter_b_phase_voltage",
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3034"],
                "multiplier": 0.1,
            },
            {
                "name": "C Phase Voltage",
                "unique": "solisconnect_inverter_c_phase_voltage",
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3035"],
                "multiplier": 0.1,
            },
            {
                "name": "A Phase Current",
                "unique": "solisconnect_inverter_a_phase_current",
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3036"],
                "multiplier": 0.1,
            },
            {
                "name": "B Phase Current",
                "unique": "solisconnect_inverter_b_phase_current",
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3037"],
                "multiplier": 0.1,
            },
            {
                "name": "C Phase Current",
                "unique": "solisconnect_inverter_c_phase_current",
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3038"],
                "multiplier": 0.1,
            },
            {"type": "reserve", "register": ["3039"]},
            {
                "name": "Working Mode",
                "unique": "solisconnect_inverter_working_mode",
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3040"],
                "multiplier": 1,
            },
            {
                "name": "Inverter Temperature",
                "unique": "solisconnect_inverter_temperature",
                "unit_of_measurement": UnitOfTemperature.CELSIUS,
                "device_class": SensorDeviceClass.TEMPERATURE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3041"],
                "multiplier": 0.1,
                "data_type": DataType.S16,
            },
            {
                "name": "Grid Frequency",
                "unique": "solisconnect_grid_frequency",
                "unit_of_measurement": UnitOfFrequency.HERTZ,
                "device_class": SensorDeviceClass.FREQUENCY,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3042"],
                "multiplier": 0.01,
            },
            {
                "name": "Inverter Status",
                "unique": "solisconnect_inverter_status",
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3043"],
                "multiplier": 1,
            },
            {
                "name": "Limited active power adjustment rated power output value",
                "unique": "solisconnect_inverter_limited_active_power_output_value",
                "unit_of_measurement": UnitOfPower.WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3044", "3045"],
                "multiplier": 1,
            },
            {
                "name": "Reactive power regulation rated power output value",
                "unique": "solisconnect_inverter_reactive_power_regulation_rated_power_output_value",
                "unit_of_measurement": UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
                "device_class": SensorDeviceClass.REACTIVE_POWER,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3046", "3047"],
                "multiplier": 1,
            },
            {"type": "reserve", "register": ["3048"]},
            {
                "name": "Actual Limited Active Power",
                "unique": "solisconnect_inverter_actual_limited_active_power",
                "unit_of_measurement": PERCENTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3049"],
                "write_register": 3051,
                "multiplier": 0.01,
                "editable": True,
                "min": 0,
                "max": 110,
            },
            {
                "name": "Actual Adjusted Power Factor",
                "unique": "solisconnect_inverter_actual_adjusted_power_factor",
                "unit_of_measurement": PERCENTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3050"],
                "multiplier": 0.01,
            },
            {
                "name": "Actual Power Factor Adjustment",
                "unique": "solisconnect_inverter_actual_power_factor_adjustment",
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3051"],
                "multiplier": 0.001,
                "editable": True,
                "min": 0,
                "max": 110,
            },
        ],
    },
    {
        "register_start": 3089,
        "poll_speed": PollSpeed.SLOW,
        "entities": [
            {
                "name": "Power Limitation Switch (89)",
                "unique": "solisconnect_power_limitation_switch",
                "state_class": SensorStateClass.MEASUREMENT,
                "hidden": True,
                "register": ["3089"],
                "multiplier": 1,
            },
        ],
    },
    {
        "register_start": 3179,
        "poll_speed": PollSpeed.SLOW,
        "entities": [
            {
                "name": "Shading MPPT Scan Enable",
                "unique": "solisconnect_shading_mppt_scan_enable",
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3179"],
                "multiplier": 0.1,
            },
            {
                "name": "Shading MPPT Scan Time Interval",
                "unique": "solisconnect_shading_mppt_scan_interval",
                "unit_of_measurement": UnitOfTime.MINUTES,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3180"],
                "multiplier": 1,
                "editable": True,
                "min": 10,
                "max": 180,
            },
        ],
    },
    {
        "register_start": 3250,
        "poll_speed": PollSpeed.FAST,
        "entities": [
            {
                "name": "Meter AC Voltage A",
                "unique": "solisconnect_meter_ac_voltage_a",
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3250"],
                "multiplier": 0.1,
            },
            {
                "name": "Meter AC Current A",
                "unique": "solisconnect_meter_ac_current_a",
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3251"],
                "multiplier": 0.01,
            },
            {
                "name": "Meter AC Voltage B",
                "unique": "solisconnect_meter_ac_voltage_b",
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3252"],
                "multiplier": 0.1,
            },
            {
                "name": "Meter AC Current B",
                "unique": "solisconnect_meter_ac_current_b",
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3253"],
                "multiplier": 0.01,
            },
            {
                "name": "Meter AC Voltage C",
                "unique": "solisconnect_meter_ac_voltage_c",
                "unit_of_measurement": UnitOfElectricPotential.VOLT,
                "device_class": SensorDeviceClass.VOLTAGE,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3254"],
                "multiplier": 0.1,
            },
            {
                "name": "Meter AC Current C",
                "unique": "solisconnect_meter_ac_current_c",
                "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
                "device_class": SensorDeviceClass.CURRENT,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3255"],
                "multiplier": 0.01,
            },
            {
                "name": "Meter AC Active Power A",
                "unique": "solisconnect_meter_ac_active_power_a",
                "unit_of_measurement": UnitOfPower.KILO_WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3256", "3257"],
                "multiplier": 0.001,
            },
            {
                "name": "Meter AC Active Power B",
                "unique": "solisconnect_meter_ac_active_power_b",
                "unit_of_measurement": UnitOfPower.KILO_WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3258", "3259"],
                "multiplier": 0.001,
            },
            {
                "name": "Meter AC Active Power C",
                "unique": "solisconnect_meter_ac_active_power_c",
                "unit_of_measurement": UnitOfPower.KILO_WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3260", "3261"],
                "multiplier": 0.001,
            },
            {
                "name": "Meter AC Active Power Total",
                "unique": "solisconnect_meter_ac_active_power_total",
                "unit_of_measurement": UnitOfPower.KILO_WATT,
                "device_class": SensorDeviceClass.POWER,
                "state_class": SensorStateClass.MEASUREMENT,
                "register": ["3262", "3263"],
                "multiplier": 0.001,
            },
        ],
    },
    {
        "register_start": 36013,
        "scan_interval": 0,
        "entities": [
            {"name": "Model No", "unique": "solisconnect_inverter_model_no", "register": ["36013"], "multiplier": 0},
            {
                "name": "Inverter EPM Firmware Version",
                "unique": "solisconnect_inverter_epm_firmware_version",
                "register": ["36014"],
                "multiplier": 0,
            },
        ],
    },
    {
        "register_start": 36022,
        "scan_interval": 60,
        "entities": [
            {
                "name": "Clock (Hours)",
                "unique": "solisconnect_inverter_clock_hours",
                "register": ["36022"],
                "multiplier": 0,
                "unit_of_measurement": UnitOfTime.HOURS,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Clock (Minutes)",
                "unique": "solisconnect_inverter_clock_minutes",
                "register": ["36023"],
                "multiplier": 0,
                "unit_of_measurement": UnitOfTime.MINUTES,
                "state_class": SensorStateClass.MEASUREMENT,
            },
            {
                "name": "Clock (Seconds)",
                "unique": "solisconnect_inverter_clock_seconds",
                "register": ["36024"],
                "multiplier": 0,
                "unit_of_measurement": UnitOfTime.SECONDS,
                "state_class": SensorStateClass.MEASUREMENT,
            },
        ],
    },
    {
        "register_start": 36028,
        "poll_speed": PollSpeed.FAST,
        "entities": [
            {
                "name": "Total Load power",
                "unique": "solisconnect_inverter_total_load_power",
                "register": ["36028", "36029"],
                "device_class": SensorDeviceClass.POWER,
                "multiplier": 100,
                "unit_of_measurement": UnitOfPower.WATT,
                "state_class": SensorStateClass.MEASUREMENT,
            }
        ],
    },
    {
        "register_start": 36050,
        "poll_speed": PollSpeed.SLOW,
        "entities": [
            {
                "name": "Total Generation Energy",
                "unique": "solisconnect_inverter_total_generation_energy",
                "register": ["36050", "36051"],
                "device_class": SensorDeviceClass.ENERGY,
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Load Total Consumption Energy",
                "unique": "solisconnect_inverter_load_total_consumption_energy",
                "register": ["36052", "36053"],
                "device_class": SensorDeviceClass.ENERGY,
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Grid Import Total Active Energy",
                "unique": "solisconnect_inverter_grid_import_total_active_energy",
                "register": ["36054", "36055"],
                "device_class": SensorDeviceClass.ENERGY,
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
            {
                "name": "Grid Export Total Active Energy",
                "unique": "solisconnect_inverter_grid_export_total_active_energy",
                "register": ["36056", "36057"],
                "device_class": SensorDeviceClass.ENERGY,
                "multiplier": 0.01,
                "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR,
                "state_class": SensorStateClass.TOTAL_INCREASING,
            },
        ],
    },
]

string_sensors_derived = [
    {
        "name": "DC Power 1",
        "unique": "solisconnect_dc_power_1",
        "device_class": SensorDeviceClass.POWER,
        "multiplier": 0.1,
        "unit_of_measurement": UnitOfPower.WATT,
        "state_class": SensorStateClass.MEASUREMENT,
        "register": ["3021", "3022"],
    },
    {
        "name": "DC Power 2",
        "unique": "solisconnect_dc_power_2",
        "device_class": SensorDeviceClass.POWER,
        "multiplier": 0.1,
        "unit_of_measurement": UnitOfPower.WATT,
        "state_class": SensorStateClass.MEASUREMENT,
        "register": ["3023", "3024"],
    },
    {
        "name": "DC Power 3",
        "unique": "solisconnect_dc_power_3",
        "device_class": SensorDeviceClass.POWER,
        "multiplier": 0.1,
        "unit_of_measurement": UnitOfPower.WATT,
        "state_class": SensorStateClass.MEASUREMENT,
        "register": ["3025", "3026"],
    },
    {
        "name": "DC Power 4",
        "unique": "solisconnect_dc_power_4",
        "device_class": SensorDeviceClass.POWER,
        "multiplier": 0.1,
        "unit_of_measurement": UnitOfPower.WATT,
        "state_class": SensorStateClass.MEASUREMENT,
        "register": ["3027", "3028"],
    },
]
